

/* Product */
export const GET_HOME_PRODUCTLIST = "GET_HOME_PRODUCTLIST"
export const GET_HOME_PRODUCTLIST_SUCCESS = "GET_HOME_PRODUCTLIST_SUCCESS"
export const GET_HOME_PRODUCTLIST_FAIL = "GET_HOME_PRODUCTLIST_FAIL"
