

/* Product */
export const GET_HOME_PRODUCTLIST = "GET_HOME_PRODUCTLIST"
export const GET_HOME_PRODUCTLIST_SUCCESS = "GET_HOME_PRODUCTLIST_SUCCESS"
export const GET_HOME_PRODUCTLIST_FAIL = "GET_HOME_PRODUCTLIST_FAIL"


//Clone Product

export const CLONE_PRODUCT = "CLONE_PRODUCT"
export const CLONE_PRODUCT_SUCCESS = "CLONE_PRODUCT_SUCCESS"
export const CLONE_PRODUCT_FAIL = "CLONE_PRODUCT_FAIL"