

/* GET CATEGORIES DROP DOWN*/
export const GET_DROP_DOWN_CATEGORY_LIST = "GET_DROP_DOWN_CATEGORY_LIST"
export const GET_DROP_DOWN_CATEGORY_LIST_SUCCESS = "GET_DROP_DOWN_CATEGORY_LIST_SUCCESS"
export const GET_DROP_DOWN_CATEGORY_LIST_FAIL = "GET_DROP_DOWN_CATEGORY_LIST_FAIL"

/* ADD CATEGORY */
export const ADD_NEW_CATEGORY = "ADD_NEW_CATEGORY"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"