export const GET_TAGS_DROP_DOWN_LIST = "GET_TAGS_DROP_DOWN_LIST"
export const GET_TAGS_DROP_DOWN_LIST_SUCCESS = "GET_TAGS_DROP_DOWN_LIST_SUCCESS"
export const GET_TAGS_DROP_DOWN_LIST_FAIL = "GET_TAGS_DROP_DOWN_LIST_FAIL"

/* ADD TAGS */
export const ADD_NEW_TAG = "ADD_NEW_TAG"
export const ADD_TAG_SUCCESS = "ADD_TAG_SUCCESS"
export const ADD_TAG_FAIL = "ADD_TAG_FAIL"
