

//Get attributes Drop Down list
export const GET_ATTRIBUTE_DROP_DOWN = "GET_ATTRIBUTE_DROP_DOWN"
export const GET_ATTRIBUTE_DROP_DOWN_SUCCESS = "GET_ATTRIBUTE_DROP_DOWN_SUCCESS"
export const GET_ATTRIBUTE_DROP_DOWN_FAIL = "GET_ATTRIBUTE_DROP_DOWN_FAIL"

//add attributes const variables

export const ADD_ATTRIBUTE = "ADD_ATTRIBUTE"
export const ADD_ATTRIBUTE_SUCCESS = "ADD_ATTRIBUTE_SUCCESS"
export const ADD_ATTRIBUTE_FAIL = "ADD_ATTRIBUTE_FAIL"