export const FORGET_PASSWORD = "FORGET_PASSWORD"
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"


//Verify Code

export const VERIFY_FORGOT_CODE = "VERIFY_FORGOT_CODE"
export const VERIFY_FORGOT_SUCCESS = "VERIFY_FORGOT_SUCCESS"
export const VERIFY_FORGOT_ERROR = "VERIFY_FORGOT_ERROR"

//Reset Code

export const RESET_FORGOT_CODE = "RESET_FORGOT_CODE"
export const RESET_FORGOT_CODE_SUCCESS = "RESET_FORGOT_CODE_SUCCESS"
export const RESET_FORGOT_CODE_ERROR = "RESET_FORGOT_CODE_ERROR"