
export const GET_TERM_DROP_DOWN_LIST = "GET_TERM_DROP_DOWN_LIST"
export const GET_TERM_DROP_DOWN_LIST_SUCCESS = "GET_TERM_DROP_DOWN_LIST_SUCCESS"
export const GET_TERM_DROP_DOWN_LIST_FAIL = "GET_TERM_DROP_DOWN_LIST_FAIL"

//add TERMS const variables

export const ADD_TERM = "ADD_TERM"
export const ADD_TERM_SUCCESS = "ADD_TERM_SUCCESS"
export const ADD_TERM_FAIL = "ADD_TERM_FAIL"
